name: apps_bmi
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.5.2 <4.0.0" # Specify a range to ensure compatibility

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_analytics: ^11.3.3 # Firebase Analytics version
  cloud_firestore: ^5.4.4

  # Add other Firebase products if needed
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bmi.jpg